@startuml
(*)  --> [StoringGenerator::nextValue] if "instance is Recorder"
-> [Yes] "Create value according to schema"
--> "Store value in file"
--> "return value"
else
--> [No] "Recreate value from file"
-> "return value"
endif
->(*)
@enduml